### PR TITLE
issue_2

### PR DESCRIPTION
**Pull request by ArpitaJJ**
properties used
opacity:0; 

issue_2

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@ArpitaJJ Good attempt! However, only 1 of the 3 properties you added is needed. Remove the other 2, and also remove the gif from the codebase (you only need the gif that you've already pasted in the PR message). Rest looks good, just make these changes in a new commit and push to this branch, to have your PR accepted

**Comment by ArpitaJJ** [comment]
ma'am I made a new commit with the mentioned changes, do I have to create a new PR as well?

**Comment by N-Shar-ma** [comment]
@ArpitaJJ Accepted! :) Next time make sure you mention the issue the PR solves (like "solves #2") in the PR message body (that's where your text and screenshot is) and not in the title since GitHub automatically detects issues mentioned in the PR message body

**Comment by N-Shar-ma** [comment]
> ma'am I made a new commit with the mentioned changes, do I have to create a new PR as well?

No this is perfectly fine. Once you make a PR you can keep updating it by pushing commits to the same branch. If things have gotten too messy (like too many code changes being reversed, etc) then you may want to make a new PR for a fresh start, but here this is okay :)

**Comment by ArpitaJJ** [comment]
Thank you ma'am ;)

**Pull request closed without merging**
