### PR TITLE
Changed background for hero tag

### PR DESCRIPTION
**Pull request by g-kabra**
Changed background to the Hero Tag to the given path, and rounded it's corners by the perfect ;) amount. Adjusted the positioning and size to suit the issue.
`
background-image: url('SVG/bgImg.svg');	
border-radius: 20px;
background-position: center;
background-size: cover;`

Larger Screens:
image

Smaller (Smartphone) Screens:
image

- [x] background addition
- [x] background adjusting

Solves #1

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@AlphaGaurav7 Really good work! However one very important thing to note is 1 PR should always only solve 1 issue. Since the hamburger issue has been closed now, please remove the changes made for those and update your PR message as well.

A tiny nitpick: for border radius, refer to the product sections' edges' CSS for consistency

**Comment by g-kabra** [comment]
Sure ma'am, had commited them before the final push, so they got included. I'll update it :)

Will change the border radius as well.

Couldn't miss the chance to have that border radius XD

**Comment by g-kabra** [comment]
Yep, all set :)

**Comment by N-Shar-ma** [comment]
@AlphaGaurav7 Good job! 

A couple suggestions for your future PRs: 
- if you update your PR such that the UI changes, be sure to update the screenshots in the PR as well, or add them as an update in a comment
- no need to copy paste the changed code in your PR description, since it's easily visible in the files changed tab of the PR. Less copy pasting means less things that might get outdated anytime your PR updates :)

**Pull request closed without merging**
