### PR TITLE
Fixed abrupt scrolling and scroll position

### PR DESCRIPTION
**Pull request by Ilikepizza2**
Issue #3  part 1 (fixed): Changed the `scroll-behaviour` to smooth scroll
Issue #3  part 2 (fixed): Adjusted the `scroll-padding-top` property to fix the issue.
GIFs attached to showcase the fixed issues:
1. Fixed issue on desktop
Issue fixed @desktop
2. Fixed issue on mobile devices
Issue fixed @mobile devices

### CODE REVIEW

**Comment by Ilikepizza2** [comment]
This solves the issue #3 Improve the behaviour of auto-scrolling links 
By mistake, I've linked it to #1 and #2.

**Comment by N-Shar-ma** [comment]
@Ilikepizza2 Works quite well! However please edit your PR message to mention #3 instead of 1 and 2. Also consider using a css variable (for ease of changing up things in the future by modifying the value of a variable instead of changing a hardcoded value everywhere) instead of 12vh (though the value is right for now!)

**Comment by Ilikepizza2** [comment]
Alright, I've edited the PR message and edited the CSS to use variables instead of hardcoded value
`scroll-padding-top: var(--header-height);`

**Comment by N-Shar-ma** [comment]
@Ilikepizza2  Good work! Liked how detailed and full of relevant gifs on different screen sizes your PR message is :)

**Comment by Ilikepizza2** [comment]
Ok thank you ma'am. :D

**Pull request closed without merging**
