### PR TITLE
Add background image to the hero section #1

### PR DESCRIPTION
**Pull request by KarthikS373**
Solved :  #1  (https://github.com/N-Shar-ma/FOSS-Weekend-Klox-Website/issues/1)
Added background to hero section 

Desktop view:
image

Mobile view:
image

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@KarthikS373 nice work, could you explain why you chose to use `-webkit-broder-radius` instead of just `border-radius`?

Also please mention issue number like "Solves #1" in the PR message (you can edit it anytime), not title, so GitHub can detect the link automatically.

**Comment by KarthikS373** [comment]
Actually there is no specific reason of choosing  -webkit-border-radius instead of just border-radius

**Comment by N-Shar-ma** [comment]
@KarthikS373 That's okay, but try to read up on what these browser prefixes, like webkit, actually mean. I'll accept this PR once you edit the PR description to mention the issue being fixed

**Comment by KarthikS373** [comment]
@N-Shar-ma Added to the description
image

**Comment by N-Shar-ma** [comment]
@KarthikS373 You've mentioned the PR number instead of the issue 😅

**Comment by KarthikS373** [comment]
Sorry Ma'am corrected it

**Pull request closed without merging**
