### PR TITLE
#3 auto scroll issue 

### PR DESCRIPTION
**Pull request by divya-nshi**
#3 Improve the behavior of auto-scrolling links 
the first issue of smooth scrolling was resolved by using scroll-behavior: smooth
the second issue of space above hidden by nav bar is resolved by using scroll padding top

https://user-images.githubusercontent.com/96721993/157808972-5bdcbe0b-dca6-427f-abf6-088e8366a4f5.mp4

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@divya-nshi Works well! :) Just remove the hamburger icon related changes then this will be accepted

**Comment by divya-nshi** [comment]
@N-Shar-ma ok ma'am

**Comment by divya-nshi** [comment]
@N-Shar-ma its done i have committed it.... do i have to request PR once again?

**Comment by N-Shar-ma** [comment]
@divya-nshi No it's alright. Once you have made a PR you can update it easily by just pushing new commits to the same branch. But if you feel things have gotten too messy, like too many changes being reverted, git history being too clumsy, etc, you can make a new PR on a new branch for a fresh start. But don't worry, here this is perfectly fine :)

**Pull request closed without merging**
