### PR TITLE
Hamburger_Issue

### PR DESCRIPTION
**Pull request by Umm-E-Kulsum**
Used the css property
 transform: rotateY(90deg);
 opacity=0;

HAMBURGER_ISSUE_FOSS

properties

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@Umm-E-Kulsum Good attempt! However, only 1 of the 3 properties you added is needed. Remove the other 2, and also remove the gif from the codebase (you only need the gif that you've already pasted in the PR message), and the commented out lines for cleaner code (I understand you experimented with different ways to fix the issue which is great, but the final code should be clean). Just make these changes in a new commit and push to this branch, to have your PR accepted.

**Comment by N-Shar-ma** [comment]
@Umm-E-Kulsum Accepted! :) Next time make sure you mention the issue the PR solves in the PR message body (that's where your gif is) since GitHub automatically detects issues mentioned in the PR message body

**Comment by Umm-E-Kulsum** [comment]
> @Umm-E-Kulsum Good attempt! However, only 1 of the 3 properties you added is needed. Remove the other 2, and also remove the gif from the codebase (you only need the gif that you've already pasted in the PR message), and the commented out lines for cleaner code (I understand you experimented with different ways to fix the issue which is great, but the final code should be clean). Just make these changes in a new commit and push to this branch, to have your PR accepted.

done @N-Shar-ma ma'am

**Comment by N-Shar-ma** [comment]
@Umm-E-Kulsum  This is better! There are still a few commented lines(the background-url ones) you need to remove though, and also the gif file. Please make these changes asap so we can wrap up this PR

**Comment by Umm-E-Kulsum** [comment]
removed the commented lines.
HAMBURGER_ISSUE_FOSS

**Comment by Umm-E-Kulsum** [comment]
> @Umm-E-Kulsum This is better! There are still a few commented lines(the background-url ones) you need to remove though, and also the gif file. Please make these changes asap so we can wrap up this PR

done ma'am @N-Shar-ma

**Comment by N-Shar-ma** [comment]
@Umm-E-Kulsum Accepted! :) Next time make sure you mention the issue the PR solves in the PR message body (that's where your gif is) since GitHub automatically detects issues mentioned in the PR message body.

Also, no need to post the same gif after every commit unless there are visible changes in the UI. Rest is good work! :)

**Pull request closed without merging**
